# Generated by Django 4.2.5 on 2023-09-18 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_balance_amount_alter_balance_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(default=0.0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
