# Generated by Django 4.2.5 on 2023-09-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_balance_user_profile_balance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
