# Generated by Django 4.2.5 on 2023-09-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fruitselection_coinselection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FruitSelection',
        ),
    ]
