# Generated by Django 4.2.5 on 2023-09-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_fruitselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinselection',
            name='transaction_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
