# Generated by Django 4.2.5 on 2023-09-20 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_coinselection_confirmed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinSelection',
            new_name='Transaction',
        ),
    ]
