# Generated by Django 4.2.5 on 2023-09-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_coinselection_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_no', models.CharField(max_length=100, unique=True)),
                ('address_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
