# Generated by Django 4.2.5 on 2023-09-24 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bitcoinaddress_ethereumaddress_usdtaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100, unique=True)),
                ('package_details', models.CharField(max_length=400)),
                ('package_range1', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='must be greater than 1')])),
                ('package_range2', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1, message='must be greater than 1')])),
            ],
        ),
    ]
