# Generated by Django 4.2.5 on 2023-09-24 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='package_range2',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Package range must be at least 1.'), django.core.validators.MaxValueValidator(10000000, message='Package range must be no more than 100.')]),
        ),
    ]
