# Generated by Django 4.2.5 on 2023-09-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_packages_package_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='package',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='my_packages', to='core.packages'),
        ),
    ]
