# Generated by Django 4.2.5 on 2023-09-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_activepackages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activepackages',
            old_name='package',
            new_name='package_name',
        ),
    ]
